on:
  push:
    branches:
    - main
  pull_request:
name: downstream
jobs:
  shared-dependencies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17]
    outputs:
      shared-dependencies-version: ${{ steps.install-shared-dependencies.outputs.VERSION }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{matrix.java}}
    - run: java -version
    - run: sudo apt-get install libxml2-utils
    - id: install-shared-dependencies
      run: echo "::set-output name=VERSION::$(./.kokoro/downstream-shared-dependencies.sh)"
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: ~/.m2
  client-libraries:
    needs: shared-dependencies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17]
        repo:
        - bigquery
        - bigqueryconnection
        - spanner
        - storage
        - pubsub
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{matrix.java}}
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
    - run: java -version
    - run: sudo apt-get install libxml2-utils
    - run: .kokoro/downstream-client-libraries.sh ${{matrix.repo}} ${{needs.install-shared-dependencies.outputs.VERSION }}