on:
  push:
    branches:
    - main
  pull_request:
name: downstream
jobs:
  client-libraries1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 17
    - run: java -version
    - uses: actions/checkout@v2
    - run: mvn clean install
    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: ~/.m2
  client-libraries:
    needs: client-libraries1
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17]
        repo:
        - eventarc
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{matrix.java}}
    - run: java -version
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
    - uses: actions/checkout@v2
      with:
        repository: googleapis/java-${{matrix.repo}}
        path: java-${{matrix.repo}}
    - run: |
        cd /home/runner/work/java-core/java-core/java-eventarc
        echo "*******************/home/runner/work/java-core/java-core********************"
        ls -R /home/runner/work/java-core/java-core
        PATH="/home/runner/work/java-core/java-core/java-eventarc"
        echo "*******************/home/runner/work/java-core/java-core/java-eventarc********************"
        ls -R ${PATH}
        #FILE_PATH="$PATH/com/google/cloud/google-cloud-shared-dependencies/${SHARED_DEPS_VERSION}/google-cloud-shared-dependencies-${SHARED_DEPS_VERSION}-tests.jar"

