on:
  push:
    branches:
    - main
  pull_request:
name: downstream
jobs:
  shared-dependencies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17]
        repo:
          - java-shared-dependencies
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{matrix.java}}
    - run: java -version
    - run: sudo apt-get install libxml2-utils
    - run: .kokoro/client-library-check.sh ${{matrix.repo}}
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: ~/.m2
    - run: echo $(ls ~/.m2)
