on:
  push:
    branches:
    - main
  pull_request:
name: downstream
jobs:
  client-libraries:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17]
        repo:
        - eventarc
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{matrix.java}}
    - run: java -version
    - uses: actions/checkout@v2
      with:
        repository: googleapis/java-${{matrix.repo}}
        path: java-${{matrix.repo}}
    - run: |
        scriptDir=$(realpath $(dirname "${BASH_SOURCE[0]}"))
        echo "This is script dir: $scriptDir"
        ls -R $scriptDir
        ## cd to the parent directory, i.e. the root of the git repo
        cd ${HOME}/java-$REPO

        PATH=${HOME}/java-core/java-core/package
        ls -R $PATH
        #FILE_PATH="$PATH/com/google/cloud/google-cloud-shared-dependencies/${SHARED_DEPS_VERSION}/google-cloud-shared-dependencies-${SHARED_DEPS_VERSION}-tests.jar"

