on:
  push:
    branches:
    - main
  pull_request:
name: downstream
jobs:
  client-libraries:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17]
        repo:
        - eventarc
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{matrix.java}}
    - run: java -version
    - uses: actions/checkout@v2
      with:
        repository: googleapis/java-${{matrix.repo}}
        path: java-${{matrix.repo}}
    - run: |
        REPO=${{matrix.repo}}
        SHARED_DEPS_VERSION=${{needs.shared-dependencies.outputs.shared-dependencies-version }}
        PATH=/home/runner/work/java-core/java-core/java-$REPO/package
        cp ${0} /home/runner/work/java-core/java-core/java-$REPO/downstream-check.sh
        chmod +x /home/runner/work/java-core/java-core/java-$REPO/downstream-check.sh
        ## cd to the parent directory, i.e. the root of the git repo
        pushd /home/runner/work/java-core/java-core/java-$REPO
        ls -R $PATH
        FILE_PATH="$PATH/${SHARED_DEPS_VERSION}/google-cloud-shared-dependencies-${SHARED_DEPS_VERSION}-tests.jar"
        cat > downstream-check.sh